// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU--6K7owq0yY4SKsLDN-XaIhofDh4ORs',
    appId: '1:766674874660:web:d8d74aef9fd408a0fd03b1',
    messagingSenderId: '766674874660',
    projectId: 'backendwrk',
    authDomain: 'backendwrk.firebaseapp.com',
    databaseURL: 'https://backendwrk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwrk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYftwROIf-M-c8YRC1kY24qPfvidkiDAw',
    appId: '1:766674874660:android:e609b2b0b7f4f21ffd03b1',
    messagingSenderId: '766674874660',
    projectId: 'backendwrk',
    databaseURL: 'https://backendwrk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwrk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyDG3i1iNLtPylhAfAGqRCLs88noZ7SU',
    appId: '1:766674874660:ios:7832ba4eea43135bfd03b1',
    messagingSenderId: '766674874660',
    projectId: 'backendwrk',
    databaseURL: 'https://backendwrk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwrk.appspot.com',
    iosBundleId: 'com.example.backendFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkyDG3i1iNLtPylhAfAGqRCLs88noZ7SU',
    appId: '1:766674874660:ios:7832ba4eea43135bfd03b1',
    messagingSenderId: '766674874660',
    projectId: 'backendwrk',
    databaseURL: 'https://backendwrk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwrk.appspot.com',
    iosBundleId: 'com.example.backendFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU--6K7owq0yY4SKsLDN-XaIhofDh4ORs',
    appId: '1:766674874660:web:225bbe239640dd17fd03b1',
    messagingSenderId: '766674874660',
    projectId: 'backendwrk',
    authDomain: 'backendwrk.firebaseapp.com',
    databaseURL: 'https://backendwrk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backendwrk.appspot.com',
  );
}
